{% set name = "freeqdsk" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/freeqdsk-{{ version }}.tar.gz
  sha256: 58192ebbd5115b38185b3b23d7c50525d63bf6cdd4531ab967cc05b67d2ed13e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - fortranformat ~=2.0
    - numpy >=1.8
    - python >=3.8

test:
  imports:
    - freeqdsk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/freeqdsk/
  summary: GEQDSK and AEQDSK tokamak equilibrium file reader/writer
  dev_url: https://github.com/freegs-plasma/FreeQDSK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LiamPattinson
