{% set name = "freeqdsk" %}
{% set version = "0.5.2" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/freeqdsk-{{ version }}.tar.gz
  sha256: 7b40430f8368a9ac130d441d43aa50944b4165c8c44fc49b752836bd8e822b4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - fortranformat ~=2.0
    - numpy >=1.22

test:
  imports:
    - freeqdsk
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/freeqdsk/
  summary: GEQDSK and AEQDSK tokamak equilibrium file reader/writer
  dev_url: https://github.com/freegs-plasma/FreeQDSK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LiamPattinson
